# Testing overlay for local development
# This overlay adjusts settings for easier testing:
# - Disables service account health checks (no auth required)
# - Disables HTTPS for simpler setup
# - Allows all egress traffic (overrides restrictive NetworkPolicy)
# - Uses host DNS for external domain resolution
# - Reduces replica count for resource constraints

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarqube-mcp

resources:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: sonarqube-mcp-config
      namespace: sonarqube-mcp
    data:
      # Disable service account health check for testing
      SERVICE_ACCOUNT_HEALTH_CHECK_ENABLED: "false"
      # Disable HTTPS for easier testing
      MCP_HTTP_HTTPS_ENABLED: "false"
      # Reduce circuit breaker timeout
      CIRCUIT_BREAKER_TIMEOUT: "2000"
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: sonarqube-mcp-secrets
      namespace: sonarqube-mcp
    stringData:
      # This will be replaced by the test script
      SONARQUBE_TOKEN: "WILL_BE_REPLACED_BY_SCRIPT"
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sonarqube-mcp
      namespace: sonarqube-mcp
    spec:
      template:
        spec:
          dnsPolicy: "Default"
          containers:
          - name: sonarqube-mcp
            startupProbe:
              httpGet:
                path: /health
                port: http
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 30
            readinessProbe:
              httpGet:
                path: /health
                port: http
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 3
  - |-
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: sonarqube-mcp
      namespace: sonarqube-mcp
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/name: sonarqube-mcp
          app.kubernetes.io/instance: production
          app.kubernetes.io/component: server
      policyTypes:
        - Ingress
        - Egress
      ingress:
        # Keep existing ingress rules
        - from:
            - namespaceSelector:
                matchLabels:
                  name: ingress-nginx
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: ingress-nginx
          ports:
            - protocol: TCP
              port: 3000
        - from:
            - namespaceSelector:
                matchLabels:
                  name: monitoring
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: prometheus
          ports:
            - protocol: TCP
              port: 9090
        - from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: sonarqube-mcp
          ports:
            - protocol: TCP
              port: 3000
            - protocol: TCP
              port: 9090
      egress:
        # Allow all egress traffic for testing
        - {}

replicas:
  - name: sonarqube-mcp
    count: 2  # Reduce replicas for testing