# OSV Scanner Configuration
# Documentation: https://google.github.io/osv-scanner/configuration/

# Ignored vulnerabilities
# These vulnerabilities are acknowledged and accepted as risk
[[IgnoredVulns]]
id = "GHSA-9965-vmph-33xx"
# Reason: validator package is dev-only dependency (not in production)
# Impact: Medium severity (CVSS 6.1)
# Status: No fix available yet
# Review date: 2025-10-14
reason = "Dev-only dependency, not exposed in production"
