apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonarqube-mcp.fullname" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
data:
  # SonarQube Configuration
  SONARQUBE_URL: {{ .Values.config.sonarqube.url | quote }}
  {{- if .Values.config.sonarqube.organization }}
  SONARQUBE_ORGANIZATION: {{ .Values.config.sonarqube.organization | quote }}
  {{- end }}
  
  # Logging Configuration
  {{- if .Values.config.logging.level }}
  LOG_LEVEL: {{ .Values.config.logging.level | quote }}
  {{- end }}
  {{- if .Values.config.logging.file }}
  LOG_FILE: {{ .Values.config.logging.file | quote }}
  {{- end }}
  
  # OpenTelemetry Monitoring (Optional)
  {{- if .Values.config.monitoring.tracing.enabled }}
  OTEL_TRACES_ENABLED: "true"
  {{- if .Values.config.monitoring.tracing.endpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.monitoring.tracing.endpoint | quote }}
  {{- end }}
  {{- if .Values.config.monitoring.tracing.serviceName }}
  OTEL_SERVICE_NAME: {{ .Values.config.monitoring.tracing.serviceName | quote }}
  {{- end }}
  {{- end }}
  
  # MCP Features (Optional)
  {{- if .Values.config.features.elicitation.enabled }}
  SONARQUBE_MCP_ELICITATION: "true"
  {{- if .Values.config.features.elicitation.bulkThreshold }}
  SONARQUBE_MCP_BULK_THRESHOLD: {{ .Values.config.features.elicitation.bulkThreshold | quote }}
  {{- end }}
  {{- if .Values.config.features.elicitation.requireComments }}
  SONARQUBE_MCP_REQUIRE_COMMENTS: "true"
  {{- end }}
  {{- if .Values.config.features.elicitation.interactiveSearch }}
  SONARQUBE_MCP_INTERACTIVE_SEARCH: "true"
  {{- end }}
  {{- end }}