apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonarqube-mcp.fullname" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
data:
  # SonarQube Configuration
  SONARQUBE_BASE_URL: {{ .Values.config.sonarqube.baseUrl | quote }}
  
  # MCP Configuration
  MCP_TRANSPORT: {{ .Values.config.transport | quote }}
  MCP_HTTP_PORT: {{ .Values.config.http.port | quote }}
  MCP_HTTP_HTTPS_ENABLED: {{ .Values.config.http.httpsEnabled | quote }}
  
  # OAuth Configuration
  {{- if .Values.config.oauth.issuer }}
  MCP_HTTP_OAUTH_ISSUER: {{ .Values.config.oauth.issuer | quote }}
  MCP_HTTP_OAUTH_AUDIENCE: {{ .Values.config.oauth.audience | quote }}
  {{- end }}
  
  # Service Account Configuration
  SERVICE_ACCOUNT_ENABLE: {{ .Values.config.serviceAccounts.enabled | quote }}
  {{- if .Values.config.serviceAccounts.enabled }}
  SERVICE_ACCOUNT_HEALTH_CHECK_ENABLED: {{ .Values.config.serviceAccounts.healthCheck.enabled | quote }}
  SERVICE_ACCOUNT_HEALTH_CHECK_INTERVAL: {{ .Values.config.serviceAccounts.healthCheck.interval | quote }}
  SERVICE_ACCOUNT_FAILOVER_ENABLED: {{ .Values.config.serviceAccounts.failover.enabled | quote }}
  {{- end }}
  
  # Monitoring Configuration
  METRICS_ENABLED: {{ .Values.config.monitoring.metrics | quote }}
  METRICS_PORT: {{ .Values.config.monitoring.metricsPort | quote }}
  {{- if .Values.config.monitoring.tracing }}
  OTEL_TRACES_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.monitoring.otelEndpoint | quote }}
  {{- end }}
  
  # Audit Configuration
  AUDIT_LOG_ENABLED: {{ .Values.config.audit.enabled | quote }}
  {{- if .Values.config.audit.enabled }}
  AUDIT_LOG_PII_REDACTION: {{ .Values.config.audit.piiRedaction | quote }}
  AUDIT_LOG_RETENTION_DAYS: {{ .Values.config.audit.retentionDays | quote }}
  {{- end }}
  
  # Performance Configuration
  HTTP_AGENT_MAX_SOCKETS: {{ .Values.config.performance.httpAgent.maxSockets | quote }}
  HTTP_AGENT_MAX_FREE_SOCKETS: {{ .Values.config.performance.httpAgent.maxFreeSockets | quote }}
  HTTP_AGENT_TIMEOUT: {{ .Values.config.performance.httpAgent.timeout | quote }}
  
  # Circuit Breaker
  {{- if .Values.config.performance.circuitBreaker.enabled }}
  CIRCUIT_BREAKER_ENABLED: "true"
  CIRCUIT_BREAKER_TIMEOUT: {{ .Values.config.performance.circuitBreaker.timeout | quote }}
  CIRCUIT_BREAKER_THRESHOLD: {{ .Values.config.performance.circuitBreaker.threshold | quote }}
  {{- end }}
  
  # Cache Configuration
  PERMISSION_CACHE_TTL: {{ .Values.config.performance.cache.permissionTTL | quote }}
  PERMISSION_CACHE_MAX_SIZE: {{ .Values.config.performance.cache.permissionMaxSize | quote }}
  TOKEN_CACHE_TTL: {{ .Values.config.performance.cache.tokenTTL | quote }}
  TOKEN_CACHE_MAX_SIZE: {{ .Values.config.performance.cache.tokenMaxSize | quote }}