{{- if .Values.secrets.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube-mcp.sonarqubeTokenSecretName" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SONARQUBE_TOKEN: {{ required "secrets.sonarqubeToken is required" .Values.secrets.sonarqubeToken | quote }}
---
{{- if .Values.config.serviceAccounts.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube-mcp.serviceAccountsSecretName" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $sa := .Values.secrets.serviceAccounts }}
  SERVICE_ACCOUNT_{{ upper $key }}_USERNAME: {{ $sa.username | quote }}
  SERVICE_ACCOUNT_{{ upper $key }}_TOKEN: {{ $sa.token | quote }}
  {{- if $sa.groupPattern }}
  SERVICE_ACCOUNT_{{ upper $key }}_GROUP_PATTERN: {{ $sa.groupPattern | quote }}
  {{- end }}
  {{- if $sa.priority }}
  SERVICE_ACCOUNT_{{ upper $key }}_PRIORITY: {{ $sa.priority | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if .Values.config.oauth.issuer }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube-mcp.oauthSecretName" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  public.pem: {{ .Values.secrets.oauthPublicKey | b64enc | quote }}
{{- end }}
---
{{- if .Values.config.http.httpsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube-mcp.tlsSecretName" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "secrets.tls.cert is required when httpsEnabled is true" .Values.secrets.tls.cert | b64enc | quote }}
  tls.key: {{ required "secrets.tls.key is required when httpsEnabled is true" .Values.secrets.tls.key | b64enc | quote }}
{{- end }}
{{- end }}