{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sonarqube-mcp.serviceAccountName" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- if and .Values.serviceAccount.create .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sonarqube-mcp.fullname" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
rules:
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sonarqube-mcp.fullname" . }}
  labels:
    {{- include "sonarqube-mcp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sonarqube-mcp.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sonarqube-mcp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}