apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-mcp
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: sonarqube-mcp
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
            limits:
              memory: "4Gi"
              cpu: "4000m"
              ephemeral-storage: "10Gi"
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=3072"
            - name: NODE_ENV
              value: "production"
      nodeSelector:
        workload-type: general
      tolerations:
        - key: "workload-type"
          operator: "Equal"
          value: "general"
          effect: "NoSchedule"