apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-mcp-config
  namespace: sonarqube-mcp
  labels:
    app.kubernetes.io/name: sonarqube-mcp
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: config
data:
  # SonarQube Configuration
  SONARQUBE_URL: "https://sonarcloud.io"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  
  # OpenTelemetry Monitoring (Optional)
  OTEL_TRACES_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  OTEL_SERVICE_NAME: "sonarqube-mcp"
  
  # MCP Features (Optional)
  SONARQUBE_MCP_ELICITATION: "true"
  SONARQUBE_MCP_BULK_THRESHOLD: "5"