name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
      
      - name: Install cross-compilation tools
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add x86_64-pc-windows-msvc
      
      - name: Build Linux binary
        run: cargo build --release --target x86_64-unknown-linux-gnu
      
      - name: Build macOS binary
        run: cargo build --release --target x86_64-apple-darwin
      
      - name: Build Windows binary
        run: cargo build --release --target x86_64-pc-windows-msvc
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/sonarqube-mcp-server
            target/x86_64-apple-darwin/release/sonarqube-mcp-server
            target/x86_64-pc-windows-msvc/release/sonarqube-mcp-server.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
